CREATE PROCEDURE [dbo].[DeleteDoctor] @Id INT

AS

BEGIN TRY 
BEGIN TRAN 

	DELETE FROM [dbo].[tDiagnosis] WHERE Id IN
		(SELECT DiagnosisId FROM [tRecord] WHERE DoctorId = @Id) 

	DELETE FROM [dbo].[tUser] 
	WHERE Id IN (SELECT UserId FROM [tDoctor] WHERE Id = @Id) 

COMMIT TRAN 
END TRY 
BEGIN CATCH 
ROLLBACK TRAN 
END CATCH

RETURN 0
